"""Initial migration.

Revision ID: b1c0d7fc349f
Revises: 
Create Date: 2024-06-03 22:06:56.262531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1c0d7fc349f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Appointments')
    op.drop_table('Departments')
    op.drop_table('Payments')
    op.drop_table('Medical_Records')
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.String(length=1),
               type_=mysql.CHAR(length=1),
               existing_nullable=False)

    op.create_table('Medical_Records',
    sa.Column('record_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('medical_history', mysql.TEXT(), nullable=True),
    sa.Column('medications', mysql.TEXT(), nullable=True),
    sa.Column('vaccination_record', mysql.TEXT(), nullable=True),
    sa.Column('lab_results', mysql.TEXT(), nullable=True),
    sa.Column('allergies', mysql.TEXT(), nullable=True),
    sa.Column('immunizations', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name='Medical_Records_ibfk_1'),
    sa.PrimaryKeyConstraint('record_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Payments',
    sa.Column('payment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payment_info', mysql.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name='Payments_ibfk_1'),
    sa.PrimaryKeyConstraint('payment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Departments',
    sa.Column('department_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('department_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('contact_info', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('department_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Appointments',
    sa.Column('appointment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('date_time', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['Users.user_id'], name='Appointments_ibfk_1'),
    sa.PrimaryKeyConstraint('appointment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
